window.esdocSearchIndex = [
  [
    "@arithmetic-type/int32/src/arithmetic/add32.js~add32",
    "function/index.html#static-function-add32",
    "<span>add32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/arithmetic/add32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/logic/and32.js~and32",
    "function/index.html#static-function-and32",
    "<span>and32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/logic/and32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/order/decreasing.js~decreasing",
    "function/index.html#static-function-decreasing",
    "<span>decreasing</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/order/decreasing.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/arithmetic/div32.js~div32",
    "function/index.html#static-function-div32",
    "<span>div32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/arithmetic/div32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/order/increasing.js~increasing",
    "function/index.html#static-function-increasing",
    "<span>increasing</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/order/increasing.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/coerce/int32.js~int32",
    "function/index.html#static-function-int32",
    "<span>int32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/coerce/int32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/limits/max.js~max",
    "variable/index.html#static-variable-max",
    "<span>max</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/limits/max.js</span>",
    "variable"
  ],
  [
    "@arithmetic-type/int32/src/limits/min.js~min",
    "variable/index.html#static-variable-min",
    "<span>min</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/limits/min.js</span>",
    "variable"
  ],
  [
    "@arithmetic-type/int32/src/arithmetic/mul32.js~mul32",
    "function/index.html#static-function-mul32",
    "<span>mul32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/arithmetic/mul32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/arithmetic/neg32.js~neg32",
    "function/index.html#static-function-neg32",
    "<span>neg32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/arithmetic/neg32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/logic/not32.js~not32",
    "function/index.html#static-function-not32",
    "<span>not32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/logic/not32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/logic/or32.js~or32",
    "function/index.html#static-function-or32",
    "<span>or32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/logic/or32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/shift/shl32.js~shl32",
    "function/index.html#static-function-shl32",
    "<span>shl32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/shift/shl32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/shift/shr32.js~shl32",
    "function/index.html#static-function-shl32",
    "<span>shl32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/shift/shr32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/arithmetic/sub32.js~sub32",
    "function/index.html#static-function-sub32",
    "<span>sub32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/arithmetic/sub32.js</span>",
    "function"
  ],
  [
    "@arithmetic-type/int32/src/logic/xor32.js~xor32",
    "function/index.html#static-function-xor32",
    "<span>xor32</span> <span class=\"search-result-import-path\">@arithmetic-type/int32/src/logic/xor32.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/arithmetic/add32.js",
    "file/src/arithmetic/add32.js.html",
    "src/arithmetic/add32.js",
    "file"
  ],
  [
    "src/arithmetic/div32.js",
    "file/src/arithmetic/div32.js.html",
    "src/arithmetic/div32.js",
    "file"
  ],
  [
    "src/arithmetic/mul32.js",
    "file/src/arithmetic/mul32.js.html",
    "src/arithmetic/mul32.js",
    "file"
  ],
  [
    "src/arithmetic/neg32.js",
    "file/src/arithmetic/neg32.js.html",
    "src/arithmetic/neg32.js",
    "file"
  ],
  [
    "src/arithmetic/sub32.js",
    "file/src/arithmetic/sub32.js.html",
    "src/arithmetic/sub32.js",
    "file"
  ],
  [
    "src/coerce/int32.js",
    "file/src/coerce/int32.js.html",
    "src/coerce/int32.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/limits/max.js",
    "file/src/limits/max.js.html",
    "src/limits/max.js",
    "file"
  ],
  [
    "src/limits/min.js",
    "file/src/limits/min.js.html",
    "src/limits/min.js",
    "file"
  ],
  [
    "src/logic/and32.js",
    "file/src/logic/and32.js.html",
    "src/logic/and32.js",
    "file"
  ],
  [
    "src/logic/not32.js",
    "file/src/logic/not32.js.html",
    "src/logic/not32.js",
    "file"
  ],
  [
    "src/logic/or32.js",
    "file/src/logic/or32.js.html",
    "src/logic/or32.js",
    "file"
  ],
  [
    "src/logic/xor32.js",
    "file/src/logic/xor32.js.html",
    "src/logic/xor32.js",
    "file"
  ],
  [
    "src/order/decreasing.js",
    "file/src/order/decreasing.js.html",
    "src/order/decreasing.js",
    "file"
  ],
  [
    "src/order/increasing.js",
    "file/src/order/increasing.js.html",
    "src/order/increasing.js",
    "file"
  ],
  [
    "src/shift/shl32.js",
    "file/src/shift/shl32.js.html",
    "src/shift/shl32.js",
    "file"
  ],
  [
    "src/shift/shr32.js",
    "file/src/shift/shr32.js.html",
    "src/shift/shr32.js",
    "file"
  ]
]